baseURL = "https://emperorkew.github.io/remcomarien.github.io/"
locale = "nl"
title = "Remco Marien"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 3

